- name: Criando Security_group
  local_action:
    module: ec2_group
    name: "{{ security_group }}"
    description: Security Group Exemplo
    region: "{{ region }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall